Fix Jenkinsfile brace mismatch

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -2,14 +2,15 @@ pipeline {
     agent any
 
     environment {
-    AWS_DEFAULT_REGION    = 'ap-south-1'
-    TF_DIR                = 'terraform/environments/dev'
-    ANSIBLE_DIR           = 'ansible'
-    AWS_ACCESS_KEY_ID     = credentials('Access_key')
-    AWS_SECRET_ACCESS_KEY = credentials('Secret_key')
-    TF_VAR_key_name       = 'key mumbai'
-    TF_VAR_admin_cidrs    = '["103.175.136.131/32"]'
-}
+        AWS_DEFAULT_REGION    = 'ap-south-1'
+        TF_DIR                = 'terraform/environments/dev'
+        ANSIBLE_DIR           = 'ansible'
+        AWS_ACCESS_KEY_ID     = credentials('Access_key')
+        AWS_SECRET_ACCESS_KEY = credentials('Secret_key')
+        TF_VAR_key_name       = 'key mumbai'
+        TF_VAR_admin_cidrs    = '["103.175.136.131/32"]'
+    }
+
     stages {
 
         stage('Checkout') {
@@ -48,15 +49,17 @@ pipeline {
                 }
             }
         }
-stage('Generate Ansible Config') {
-    steps {
-        dir(TF_DIR) {
-            script {
-                env.BASTION_IP = sh(script: "terraform output -raw bastion_public_ip", returnStdout: true).trim()
+
+        stage('Generate Ansible Config') {
+            steps {
+                dir(TF_DIR) {
+                    script {
+                        env.BASTION_IP = sh(script: "terraform output -raw bastion_public_ip", returnStdout: true).trim()
+                    }
+                }
             }
         }
-    }
-}
+
         stage('Ansible: Install Requirements') {
             steps {
                 dir(ANSIBLE_DIR) {
@@ -73,18 +76,19 @@ stage('Generate Ansible Config') {
             }
         }
 
-       stage('Verify Infrastructure') {
-    steps {
-        dir(TF_DIR) {
-            sh '''
-                echo "bastion reachable (Jenkins is running on it)"
-                for ip in $(terraform output -json private_node_ips | python3 -c "import sys,json; print(' '.join(json.load(sys.stdin).values()))"); do
-                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/key-mumbai.pem ubuntu@$ip "curl -sf http://localhost/health" || echo "WARN: $ip health check failed"
-                done
-            '''
+        stage('Verify Infrastructure') {
+            steps {
+                dir(TF_DIR) {
+                    sh '''
+                        echo "bastion reachable (Jenkins is running on it)"
+                        for ip in $(terraform output -json private_node_ips | python3 -c "import sys,json; print(' '.join(json.load(sys.stdin).values()))"); do
+                          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key-mumbai.pem ubuntu@$ip "curl -sf http://localhost/health" || echo "WARN: $ip health check failed"
+                        done
+                    '''
+                }
+            }
         }
     }
-}
 
     post {
         success {
